name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Get-Versions:
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.Get_Versions.outputs.versions }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Minecraft Versions
        id: Get_Versions
        run: |
          VERSIONS=$(find versions -maxdepth 1 -type d -name "[0-9]*.[0-9]*" | xargs -I {} basename {} | sort -V | jq -R . | jq -s -c .)
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT
  Build-Matrix:
    runs-on: ubuntu-24.04
    needs: Get-Versions
    strategy:
      matrix:
        minecraft_version: ${{ fromJson(needs.Get-Versions.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build For ${{ matrix.minecraft_version }}
        run: ./gradlew :${{ matrix.minecraft_version }}:build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.minecraft_version }}
          path: versions/${{ matrix.minecraft_version }}/build/libs/*.jar
          if-no-files-found: error
  Publish-Modrinth-Matrix:
    runs-on: ubuntu-24.04
    needs: [Build-Matrix, Get-Versions]
    strategy:
      matrix:
        minecraft_version: ${{ fromJson(needs.Get-Versions.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract Version Info
        id: Version_Info
        run: |
          MOD_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          MOD_ID=$(grep '^id=' gradle.properties | cut -d'=' -f2)
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
          echo "mod_id=$MOD_ID" >> $GITHUB_OUTPUT
          echo "mod_name=Carpet RMS Addition" >> $GITHUB_OUTPUT
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.minecraft_version }}
          path: versions/${{ matrix.minecraft_version }}/build/libs/
      - name: Publish To Modrinth
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            versions/${{ matrix.minecraft_version }}/build/libs/*.jar
          name: ${{ format('{0} v{1} for MC {2}', 
                 steps.Version_Info.outputs.mod_name, 
                 steps.Version_Info.outputs.mod_version,
                 matrix.minecraft_version) }}
          version: ${{ format('v{0}-mc{1}', 
                    steps.Version_Info.outputs.mod_version,
                    matrix.minecraft_version) }}
          version-type: release
          loaders: fabric
          game-versions: |
            ${{ matrix.minecraft_version }}
          dependencies: |-
            carpet(required)
  Github-Release:
    runs-on: ubuntu-24.04
    needs: [Build-Matrix, Get-Versions]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract Version Info
        id: Version_Info
        run: |
          MOD_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          MOD_ID=$(grep '^id=' gradle.properties | cut -d'=' -f2)
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
          echo "mod_id=$MOD_ID" >> $GITHUB_OUTPUT
          echo "mod_name=Carpet RMS Addition" >> $GITHUB_OUTPUT
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Reorganize Artifacts
        run: |
          mkdir -p release_files
          for version_dir in artifacts/build-*/; do
            version=$(basename "$version_dir" | sed 's/build-//')
            cp "$version_dir"*.jar release_files/
          done
          find release_files -name "*.jar" -type f
      - name: Delete Existing Release And Tag If Exists
        run: |
          VERSION=${{ steps.Version_Info.outputs.mod_version }}
          TAG="v$VERSION"
          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release delete "$TAG" --yes
          fi
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            git push --delete origin "$TAG" || true
            git tag -d "$TAG" || true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish To GitHub Release
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            release_files/*.jar
          version: ${{ format('v{0}', steps.Version_Info.outputs.mod_version) }}
          github-tag: ${{ format('v{0}', steps.Version_Info.outputs.mod_version) }}
          github-generate-changelog: true
